title   EndeavourOS with open source drivers: All GPUs
sort-key  A
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=n module_blacklist=pcspkr,nvidia,nvidia_drm,nvidia_modeset,nvidia_uvm nouveau.modeset=1 i915.modeset=1 radeon.modeset=1 nvme_load=yes quiet splash loglevel=3 nowatchdog mitigations=auto systemd.show_status=auto rd.luks=0 rd.lvm=0 rd.md=0
