# Performance tweaks applied at boot
w /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/defrag - - - - defer+madvise
w /proc/sys/vm/compaction_proactiveness - - - - 0
